django_project/urls.py
# path('accounts/', include('django.contrib.auth.urls')),

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('projetos/', include('project.urls') ),
    path('servicos/', include('service.urls')),
    path('users/', include('user.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import mainTeste


urlpatterns = [
    path('', mainTeste, name='home'),
]

project/urls.py
from django.urls import path
from project.views import listProjects, saveProject, viewProject, editProject, delete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    
    path('', login_required(listProjects, login_url='loginView') , name='projects'),
    path('<int:page>/', login_required(listProjects, login_url='loginView'), name='projects'),
    path('criar/', login_required(saveProject, login_url='loginView'), name='createProject'),
    path('projeto/<int:pk>/', login_required(viewProject, login_url='loginView'), name='viewProject'),
    path('editar/<int:pk>/', login_required(editProject, login_url='loginView'), name='editProject'),
    path('delete/<int:pk>/', login_required(delete, login_url='loginView'), name='deleteProject'),

]

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Project(models.Model):
    
    name = models.CharField(max_length=200)
    manager = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    deadline = models.DateField()
    status = models.CharField(max_length=200)
    budget = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #spentBudget = models.IntegerField(null=True, blank=True)

service/models.py
from django.db import models
from project.models import Project

# Create your models here.
class Service(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.CharField(max_length=200)

project/forms.py
from django import forms
from project.models import Project

STATUS_CHOICES = [
    ('Em planejamento', 'Em planejamento'),
    ('Em desenvolvimento', 'Em desenvolvimento'),
    ('Concluído', 'Concluído'),
    ('Cancelado', 'Cancelado'),
]

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'manager', 'status', 'budget', 'deadline']

        widgets = {
            'name': forms.TextInput(attrs={
                'spellcheck': 'true',
                'class': 'form-control',
                'placeholder': 'Nome do projeto',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Descrição rápida do projeto',
                'spellcheck': 'true'       
            }),
            'manager': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Gerente do projeto'
            }),
            'status': forms.Select(choices=STATUS_CHOICES, attrs={
                'class': 'form-control',
                'placeholder': 'Status do projeto',          
            }),
            'budget': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Exemplo: 23000,95',  
                'step': 0.01    
            }),
            'deadline': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',            
             })
        }

project/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from project.forms import ProjectForm
from project.models import Project
from django.http import HttpResponse
from django.contrib import messages
from service.forms import ServiceForm
from service.models import Service
from django.core.paginator import Paginator

def listProjects(request, page=1):
    data = {}
    projects = Project.objects.filter(user=request.user)

    if request.GET.get('search'):
        projects = Project.objects.filter(name__contains=request.GET.get('search'), user=request.user)
   
    paginator = Paginator(projects, 10) # Show 10 contacts per page.
   
    data['projects'] = paginator.get_page(page)

    return render(request, 'project/list_projects.html', data)


def saveProject(request):
    if request.method == 'GET':
        data = {}
        data['form'] = ProjectForm()
        return render(request, 'project/form_project.html', data)

    elif request.method == 'POST':
        form = ProjectForm(request.POST or None)

        if form.is_valid():
            try:
                project = form.save(commit=False)
                project.user = request.user
                project.save()
                messages.success(request, "Projeto salvo!")
                return redirect('projects')

            except NameError: 
                print(NameError)
                messages.error(request, "Erro ao salvar o projeto!")
                return redirect('projects')
        else:
            messages.error(request, "Erro ao salvar o projeto, dados invalidos!")
            return redirect('projects')

            
def viewProject(request, pk):
    data = {}
    #data['project'] = Project.objects.get(pk=pk, user=request.user)
    data['project'] = get_object_or_404(Project, pk=pk, user=request.user)
    services = Service.objects.filter(project=pk)
    
    paginator = Paginator(services, 10)
    data['services'] = paginator.get_page(1)

    spentBudget = 0

    for servicBudget in data['services']:
        spentBudget += servicBudget.price
   
    data['serviceForm'] = ServiceForm()
    data['spentBudget'] = spentBudget

    return render(request, 'project/view_project.html', data)


def editProject(request, pk):  
    data = {}
    data['project'] = get_object_or_404(Project, pk=pk, user=request.user)
    data['form'] = ProjectForm(instance=data['project'])
    
    if request.method == 'POST':
        form = ProjectForm(request.POST or None, instance=data['project'])

        if form.is_valid():
            try:
                data['project'] = form.save()
            except NameError:
                print(NameError)
         
            data['form'] = ProjectForm(instance=data['project'])

            return render(request, 'project/form_project.html', data)
        else:
            return render(request, 'project/form_project.html', data)

    return render(request, 'project/form_project.html', data)


def delete(request, pk):
    project = Project.objects.get(pk=pk, user=request.user)

    try:
        project.delete()
        messages.success(request, f"Projeto {project.name} deletado!")
    except NameError:
        messages.error(request, f"Erro ao deletar o projeto '{project.name}'!")

    return redirect('projects')

project/templates/project/form_project.html
{% if project %}
  {% include 'project/includes/head.html' with title='- Editar projeto' %}
{% else %}
  {% include 'project/includes/head.html' with title='- Novo projeto' %}
{% endif %}

{% include 'includes/header.html' %}
{% include 'includes/nav.html' with location='create' %}

<!DOCTYPE html>
<html lang="pt-BR">

<main>

  <div class="container-sm">

    <div class="mt-3">

      <div id="alert"></div>

      <form {% if project %} onsubmit="editProject(event);" {% endif %} id="form" class="mb-5 mt-5 card" style="max-width: 600px; margin:auto;"
        action="{% if project %}{% url 'editProject' project.id %}{% else %}{% url 'createProject' %}{% endif %}"
        method="POST">

        {% if project %}
          <h1 class="mt-4">Editar projeto</h1>
        {% else %}
          <h1 class="mt-4">Cadastrar projeto</h1>
        {% endif %}

        {% comment %} {{ form.as_p }} {% endcomment %}
        {% comment %} {{ form.name.value }} {% endcomment %}

        {% csrf_token %}

        <div class="form-group mt-5">
          <label for="id_name" class="labelForm">Nome</label>
          {{ form.name }}
        </div>

        <div class="form-group mt-3">
          <label for="id_manager" class="labelForm">Gerente</label>
          {{ form.manager }}
        </div>

        <div class="form-group mt-3" style="width: 250px;">
          <label for="id_status">Status</label>
          {{ form.status }}
        </div>

        <div class="form-group mt-3" style="width: 250px;">
          <label for="id_budget">Orçamento</label>
          {{ form.budget }}
        </div>

        <div class="form-group mt-3" style="width: 150px;">
          <label for="id_deadline" class="labelForm">Prazo</label>
          {{ form.deadline }}
        </div>

        <div class="form-group mt-3" oninput="result.value=id_description.value.length">
          <label for="id_description" class="labelForm">Descrição</label>
          {{ form.description }}
          <small>
            <output id="result">{{ form.description.value|length }}</output>/200
          </small>
        </div>

        <input style="width: 100px;" class="btn btn-info mt-2 mb-5" type="submit" value="Salvar">

      </form>

    </div>
  </div>

</main>

{% include 'includes/footer.html' %}

{% load static %}
<script src="{% static 'project/js/project.js' %}"></script>

project/templates/project/index.html
{% include 'includes/header.html' with title='- Seus projetos' location='home' %}
{% load static %}

<main>
  <div class="container">

    <h1 class="mt-2 ms-5">Seus projetos</h1>

    {% if messages %}
    {% for message in messages %}
    <div id="alert" class="alert {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show "
      role="alert">
      <span> {{ message }} </span>
      <button type="button" class="btn-close" onclick="hidenAlert()"></button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="d-flex justify-content-center flex-wrap flex-row">

      {% for project in projects %}

      <div class="card mt-5">
        <div style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title mb-2">{{ project.name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Gerente: {{ project.manager }}</h6>
            <p class="card-text">
              Status: {{ project.status }}
              {% if project.status == 'Em desenvolvimento' %}
              <div class="progress" style="width: 100%;">
                <div class="progress-bar progress-bar-striped bg-primary" role="progressbar"
                  aria-label="Success striped example" style="width: 50%" aria-valuenow="25" aria-valuemin="0"
                  aria-valuemax="100"></div>
              </div>

              {% elif project.status == 'Em planejamento' %}
              <div class="progress" style="width: 100%;">
                <div class="progress-bar progress-bar-striped bg-info" role="progressbar"
                  aria-label="Success striped example" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
                  aria-valuemax="100"></div>
              </div>

              {% elif project.status == 'Concluído' %}
              <div class="progress" style="width: 100%;">
                <div class="progress-bar progress-bar-striped bg-success" role="progressbar"
                  aria-label="Success striped example" style="width: 100%" aria-valuenow="25" aria-valuemin="0"
                  aria-valuemax="100"></div>
              </div>

              {% elif project.status == 'Cancelado' %}
              <div class="progress" style="width: 100%;">
                <div class="progress-bar progress-bar-striped bg-danger" role="progressbar"
                  aria-label="Success striped example" style="width: 100%" aria-valuenow="25" aria-valuemin="0"
                  aria-valuemax="100"></div>
              </div>

              {% endif %}

            </p>
            <p class="card-text">Prazo: {{ project.deadline|date:"d/m/y" }}</p>

            <div>

              <a href="{% url 'viewProject' project.id %}" class="btn btn-info option">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff"
                  class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                  <path
                    d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
                </svg>
              </a>

              <a href="{% url 'editProject' project.id %}" class="btn btn-warning option">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-pencil-square"
                  viewBox="0 0 16 16">
                  <path
                    d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                  <path fill-rule="evenodd"
                    d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                </svg>
              </a>

              <button
                onclick="deleteConfirm( 'Realmente deseja deletar o projeto {{ project.name }}' , `{% url 'deleteProject' project.id %}`)"
                class="btn btn-danger option">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-trash3-fill"
                  viewBox="0 0 16 16">
                  <path
                    d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                </svg>
              </button>

            </div>

          </div>
        </div>
      </div>
      {% endfor %}

    </div>

  </div>

  <div id="plusButton">
    <a title="Novo projeto" class="btn border-0 " href="{% url 'createProject' %}">
      <img class="rounded-circle bg-light" src="{% static 'project/img/plus.svg' %}" alt="">
    </a>
  </div>

  <hr class="m-3">

  <nav aria-label="Page navigation example ">

    <ul class="pagination justify-content-center ">

      {% if projects.has_previous %}
      <li class="page-item">
        <a class="page-link page"
          href="{% url 'projects' projects.previous_page_number %}{% if request.GET.search %}?search={{ request.GET.search }}{% endif %}">
          <span>&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for page in projects.paginator.page_range %}
      <li class="page-item">
        <a class="page-link page {% if projects.number == page %} bg-info {% endif %}"
          href="{% url 'projects' page %}{% if request.GET.search %}?search={{ request.GET.search }}{% endif %}">{{ page }}
        </a>
      </li>
      {% endfor %}

      {% if projects.has_next %}
      <li class="page-item">
        <a class="page-link page"
          href="{% url 'projects' projects.next_page_number %}{% if request.GET.search %}?search={{ request.GET.search }}{% endif %}">
          <span>&raquo;</span>
        </a>
      </li>
      {% endif %}

    </ul>
   
  </nav>

</main>

{% include 'includes/footer.html' %}

project/templates/project/view_project.html
{% include 'project/includes/head.html' with title='- Projeto: '|add:project.name %}
{% include 'includes/header.html' %}
{% include 'includes/nav.html' %}

<main>

  <!-- ------------- Modal start ---------------- -->

  <div id="divModal" onclick="modalService(`{% url 'saveService' project.id %}`, 'none')"></div>

  <!-- onsubmit="editService(event)" -->
  <form id="formService" action="{% url 'saveService' project.id %}" method="post">

    {% csrf_token %}

    <div class="d-flex flex-row justify-content-between">
      <h5 class="card-title">Cadastrar serviço</h5>
      <button type="button" onclick="modalService(`{% url 'saveService' project.id %}`, 'none')" class="btn-close"
        id="closeServiceForm" aria-label="Close"></button>
    </div>

    <div id="inputsService">

      <div class="mt-2">
        <label class="labelForm" for="id_name">Nome do serviço</label>
        {{ serviceForm.name }}
      </div>

      <div class="mt-2" style="width: 10rem">
        <label class="labelForm" for="id_price">Custo</label>
        {{ serviceForm.price }}
      </div>

      <div class="mt-2" oninput="quantityCararacters.value=id_description.value.length">
        <label class="labelForm" for="id_description">Descrição</label>
        {{ serviceForm.description}}
        <small>
          <output id="quantityCararacters">{{ serviceForm.description.value|length }}</output>/200
        </small>
      </div>

      <input class="btn btn-info mt-5" type="submit" value="Salvar">
      <input class="btn btn-danger mt-5" type="button"
        onclick="modalService(`{% url 'saveService' project.id %}`, 'none')" value="Cancelar">

    </div>
  </form>

  <!-- ------------- Modal end ---------------- -->

  <div class="container mt-5">


    {% if messages %}
    {% for message in messages %}
    <div id="alert" class="alert {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show mb-5"
      role="alert">
      <span> {{ message }} </span>
      <button type="button" class="btn-close" onclick="hidenAlert()"></button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="card mt-3">
      <div>
        <h5 class="card-title mb-2">{{ project.name }}</h5>
        <span class="card-text">Gerente: {{ project.manager }}</span> <br>
        <span class="card-text">Prazo: {{ project.deadline|date:"d/m/y" }}</span> <br>

        {% load mathfilters %}
        <span class="card-text">
          Orçamento:
          {% if project.budget %}
          R$ {{ project.budget }} |
          Gasto: R$ {{ spentBudget }} |
          Disponível: R$ {{ project.budget|sub:spentBudget }}
          {% else %}
          Não definido
          {% endif %}
        </span> <br>

        <p class="card-text">
          Status: {{ project.status }}
        </p>

        {% if project.status == 'Em desenvolvimento' %}
        <div class="progress">
          <div class="progress-bar progress-bar-striped bg-primary" role="progressbar"
            aria-label="Success striped example" style="width: 50%" aria-valuenow="25" aria-valuemin="0"
            aria-valuemax="100"></div>
        </div>

        {% elif project.status == 'Em planejamento' %}
        <div class="progress">
          <div class="progress-bar progress-bar-striped bg-info" role="progressbar" aria-label="Success striped example"
            style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        {% elif project.status == 'Concluído' %}
        <div class="progress" style="width: 100%;">
          <div class="progress-bar progress-bar-striped bg-success" role="progressbar"
            aria-label="Success striped example" style="width: 100%" aria-valuenow="25" aria-valuemin="0"
            aria-valuemax="100"></div>
        </div>

        {% elif project.status == 'Cancelado' %}
        <div class="progress">
          <div class="progress-bar progress-bar-striped bg-danger" role="progressbar"
            aria-label="Success striped example" style="width: 100%" aria-valuenow="25" aria-valuemin="0"
            aria-valuemax="100"></div>
        </div>

        {% endif %}

        <p class="mb-3 mt-1 text-muted">{{ project.description }}</p>

        <div>

          <a href="{% url 'editProject' project.id %}" class="btn btn-warning option">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-pencil-square"
              viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
            </svg>
          </a>

          <button
            onclick="deleteConfirm( 'Realmente deseja deletar o projeto {{ project.name }}' , `{% url 'deleteProject' project.id %}`)"
            class="btn btn-danger option">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-trash3-fill"
              viewBox="0 0 16 16">
              <path
                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
            </svg>
          </button>

        </div>

      </div>
    </div>

    <div class="card mt-5">

      <button class="btn btn-light ms-3 d-flex flex-row flex-nowrap align-items-center"
        onclick="searchService(event, true)" title="Atualizar">
        <h5 class="card-title">Serviços</h5>
        {% load static %}
        <img class="ms-1" src="{% static 'img/arrow-repeat.svg' %}" alt="">
      </button>

      <div class="d-flex flex-row flex-wrap justify-content-between">

        <button class="btn btn-info text-light m-3"
          onclick="modalService( `{% url 'saveService' project.id %}`, 'block')">
          Adicionar serviço
          {% load static %}
          <img src="{% static 'img/plus.svg' %}" class="bg-light rounded-pill" width="30" alt="">
        </button>

        <form action="{% url 'listServices' project.id 1 %}" onsubmit="searchService(event)" method="get"
          id="searchService" class="m-3" role="search">

          <div class="input-group">
            <span class="input-group-text bg-info border-0" id="basic-addon1">
              {% load static %}
              <img src="{% static 'img/search.svg' %}" alt="">
            </span>
            <input type="search" spellcheck="true" name='search' id='search' class="form-control" placeholder="Buscar serviço"
              aria-label="Search" aria-describedby="basic-addon1">
          </div>

        </form>

      </div>

      <div>
        {% if services|length == 0 %}
        <span class="text-muted">Ainda não a serviços cadastrados</span>
        {% endif %}
      </div>

      <div id="listServices">
        {% for service in services %}
        <div class="m-3 rounded-3 shadow p-3">

          <h6 class="card-title mb-2">{{ service.name }}</h6>
          <p>Custo: R$ {{ service.price }}</p>
          <p class="text-muted mb-3">Descrição: {{ service.description }}</p>

          <div>

            <button
              onclick="setValuesService('{{ service.name }}', {{ service.price }}, '{{ service.description }}', `{% url 'editService' project.id service.id %}`)"
              class="btn btn-warning option">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-pencil-square"
                viewBox="0 0 16 16">
                <path
                  d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd"
                  d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
              </svg>
            </button>

            <button
              onclick="deleteConfirm('Realmente deseja deletar o serviço {{ service.name }}', `{% url 'deleteService'  project.id service.id %}` )"
              href="{% url 'deleteService' project.id service.id %}" class="btn btn-danger option">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-trash3-fill"
                viewBox="0 0 16 16">
                <path
                  d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
              </svg>
            </button>

          </div>

        </div>
        {% endfor %}

        {% if services|length > 0 %}

        <hr class="m-3">

        <nav aria-label="Page navigation example ">

          <ul class="pagination justify-content-center ">

            {% if services.has_previous %}
            <li class="page-item">
              <button class="page-link page" onclick='paginatorServices(`{% url ' listServices' project.id
                services.previous_page_number %}`)'>&laquo;</button>
            </li>
            {% endif %}

            {% for page in services.paginator.page_range %}
            <li class="page-item"><button onclick='paginatorServices(`{% url ' listServices' project.id page %}`)'
                class="page-link {% if services.number == page %} bg-info {% endif %} page">{{ page }}</button></li>
            {% endfor %}

            {% if services.has_next %}
            <li class="page-item">
              <button class="page-link page" onclick='paginatorServices(`{% url ' listServices' project.id
                services.next_page_number %}`)'>&raquo;</button>
            </li>
            {% endif %}

          </ul>

        </nav>

        {% endif %}

      </div>

    </div>

  </div>

</main>


{% include 'includes/footer.html' %}

{% load static %}
<script src="{% static 'project/js/project.js' %}"></script>