django_project/urls.py
# path('accounts/', include('django.contrib.auth.urls')),

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('projetos/', include('project.urls') ),
    path('servicos/', include('service.urls')),
    path('users/', include('user.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import mainTeste


urlpatterns = [
    path('', mainTeste, name='home'),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('login/', views.loginView, name='loginView'),
    path('cadastro/', views.register, name='register'),
    path('logout/', views.logoutView, name='logoutView'),
    path('usuario/', login_required(views.userData, login_url='loginView'), name='userData'),
    path('deletar-user/', login_required(views.removeUser, login_url='loginView'), name='removeUser'),
    path('upload-image-user/', login_required(views.imageUserSave, login_url='loginView'), name='imageUserSave'),
    path('update-image-user/<int:pk>', login_required(views.updateImageUser, login_url='loginView'), name='updateImageUser'),
    path('delete-image-user/<int:pk>', login_required(views.deleteImageUser, login_url='loginView'), name='deleteImageUser'),
   
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')

   

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Image


# Create your forms here.
class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control'
        }))

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }))

    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }))

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }))

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }))
     
    class Meta:
        model = User
        fields = ("username", "first_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class ImageForm(forms.ModelForm):
    """Form for the image model"""

    image = forms.ImageField(
        required=True,
        widget=forms.FileInput(attrs={
            'class': 'form-control'
        }))

    class Meta:
        model = Image
        fields = ('image',)

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import NewUserForm, ImageForm
from .models import Image
import os
from django.conf import settings


# Create your views here.
def loginView(request):
    if request.user.is_authenticated:
        return redirect('projects')
    
    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('projects')
            
        else:
            messages.error(request, 'Erro ao logar, verifique seu e-mail e senha!')
            return redirect('loginView')
    else:        
        return render(request, 'user/login.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('projects')  
    
    if request.method == "POST":
        form = NewUserForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("projects")
        else:
            messages.error(request, "Registro sem sucesso. Informações inválidas.")
            return redirect("register")
    else:        
        data = {}
        data['form'] = NewUserForm()
        return render(request, 'user/form_user.html', data)

def logoutView(request):
    logout(request)
    return redirect('home')

def userData(request):
    data = {}
    data['form'] = NewUserForm(instance=request.user)
    data['imageForm'] = ImageForm()

    if Image.objects.filter(user=request.user).exists():
        data['imageUser'] = Image.objects.filter(user=request.user)[0]

    if request.method == "POST":
        form = NewUserForm(request.POST or None, instance=request.user)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Alteração de dados feita com sucesso.")
            return redirect("userData")
        else:
            messages.error(request, "Alteração de dados sem sucesso. Informações inválidas.")
            return redirect("userData")

    return render(request, 'user/form_user.html', data)

def removeUser(request):

    try:
        request.user.delete()
    except NameError:
        messages.error(request, "Error:" + NameError)

    return redirect("loginView")


""" ------ Start views image user --------- """

#https://djangocentral.com/uploading-images-with-django/
def imageUserSave(request):
    form = ImageForm(request.POST or None, request.FILES)

    if form.is_valid():
        image = form.save(commit=False)
        image.user = request.user
        image.save()
        messages.success(request, "Imagem salva.")
    else:
        messages.error(request, "Erro ao salvar imagem.")

    return redirect("userData")

def updateImageUser(request, pk):
    
    try:
        imageGet = get_object_or_404(Image, pk=pk, user=request.user)
        oldImageUrl = (f'{settings.BASE_DIR}/{imageGet.image.url}')
        
        form = ImageForm(request.POST, request.FILES, instance=imageGet)

        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()

            os.remove(oldImageUrl)

            messages.success(request, "Imagem editada.")
            return redirect("userData")

        else:
            messages.error(request, "Erro ao editar imagem.")
            return redirect("userData")

    except:
        messages.error(request, "Erro ao editar imagem.")
        return redirect("userData")
    
def deleteImageUser(request, pk):
    imageGet = get_object_or_404(Image, pk=pk, user=request.user)

    try:
        os.remove(f'{settings.BASE_DIR}/{imageGet.image.url}')
        imageGet.delete()
        messages.success(request, "Imagem removida.")
    except:
        messages.error(request, "Erro ao remover imagem.")
    
    return redirect("userData")

""" ------ End views image user --------- """

user/templates/user/form_user.html
{% load static %}
{% if user.is_authenticated %}
    {% include 'user/includes/head.html' with title="- Dados da conta" %}
    {% include 'includes/header.html' %}
    {% include 'includes/nav.html' %}
{% else %}
    {% include 'user/includes/head.html' with title="- Registro" %}
    {% include 'includes/header.html' %}
{% endif %}

<main>

    {% if messages %}
        {% for message in messages %}
            <div id="alert"
                class="alert rounded-0 {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show "
                role="alert">
                <span> {{ message }} </span>
                <button type="button" class="btn-close" onclick="hidenAlert()"></button>
            </div>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}

        <form method="post" class="mt-5"
            action="{% if imageUser %} {% url 'updateImageUser' imageUser.id %} {% else %} {% url 'imageUserSave' %} {% endif %}"
            enctype="multipart/form-data">

            <div class="card">

                {% if imageUser %}
                    <img id="personCicle" src="{{ imageUser.image.url }}" width="70" height="70" alt="">
                {% else %}
                    <img id="personCicle" src="{% static 'user/img/person-circle.svg' %}" width="70" height="70" alt="">
                {% endif %}

                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_image">Imagem do perfil</label>
                    {{ imageForm.image }}
                </div>

                {% if imageUser %}
                    <div class="btn-group" role="group">
                        <button class="btn btn-warning" type="submit">
                            Atualizar imagem
                        </button>
                        <button class="btn btn-danger" onclick="deleteConfirm('Realmente deseja remover a foto do perfil?', `{% url 'deleteImageUser' imageUser.id %}`)">
                            Remover imagem
                        </button>
                    </div>
                {% else %}
                    <button class="btn btn-info" type="submit">
                        Salvar imagem
                    </button>
                {% endif %}

            </div>
        </form>

    {% endif %}

    <form class="mt-5"
        action="{% if request.user.is_authenticated %} {% url 'userData' %} {% else %} {% url 'register' %} {% endif %}"
        method="post">

        {% csrf_token %}

        <div class="card d-flex flex-column justify-content-center">

            {% if not user.is_authenticated %}
                <img id="personCicle" src="{% static 'user/img/person-circle.svg' %}" width="70" height="70" alt="">
            {% endif %}

            <h1 class="titleH1">
                {% if user.is_authenticated %}
                    Seus dados
                {% else %}
                    Cadastrar-se
                {% endif %}
            </h1>

            <div class="mt-2">
                <label class="labelForm" for="id_username">Nome de usuário</label>
                {{ form.username }}
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_username">Nome</label>
                {{ form.first_name }}
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_email">E-mail</label>
                {{ form.email }}
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_password1">Senha</label>
                {{ form.password1 }}
                <small>
                    <ul>
                        <li>Sua senha não pode ser muito parecida com suas informações pessoais.</li>
                        <li>Sua senha deve conter pelo menos 8 caracteres.</li>
                        <li>Sua senha não pode ser uma senha de usuário comum.</li>
                        <li>Sua senha não pode ser totalmente numérica.</li>
                    </ul>
                </small>
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_password2">Confirmar senha</label>
                {{ form.password2 }}
            </div>

            {% if user.is_authenticated %}
            <input class="btn btn-info mt-4" type="submit" value="Salvar"">
                <button class=" btn btn-danger mt-1"
                onclick="deleteConfirm('Realmente deseja deletar esta conta permanentemente?', `{% url 'removeUser' %}`)">Deletar
            conta</button>
            {% else %}
            <input class="btn btn-info mt-3" type="submit" value="Cadastrar">
            <a class="link-secondary mt-1 text-center" href="{% url 'loginView' %}">Entrar</a>
            {% endif %}

        </div>
    </form>

</main>

{% include 'includes/footer.html' %}

user/templates/user/login.html
{% load static %}
{% include 'user/includes/head.html' with title="- Login" %}
{% include 'includes/header.html' %}

<main>

    {% if messages %}
    {% for message in messages %}
    <div id="alert"
        class="alert rounded-0 {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show "
        role="alert">
        <span> {{ message }} </span>
        <button type="button" class="btn-close" onclick="hidenAlert()"></button>
    </div>
    {% endfor %}
    {% endif %}

    <form class="mt-5" action="{% url 'loginView' %}" method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div class="card d-flex flex-column justify-content-center">

            <img id="personCicle" src="{% static 'user/img/person-circle.svg' %}" width="70" alt="">

            <h1 class="titleH1" >Login</h1>

            <div>
                <label for="id_username">Username</label>
                <input id="id_username" name="username" class="form-control" type="text">
            </div>

            <div class="mt-2">
                <label for="id_password">Senha</label>
                <input class="form-control" name="password" id="id_password" type="password">
            </div>

            <input class="btn btn-info mt-3" type="submit" value="Entrar">
            <a class="link-secondary mt-1 text-center" href="{% url 'register' %}">Cadastrar-se</a>

        </div>
    </form>

</main>

{% include 'includes/footer.html' %}

user/templates/user/user_data.html
{% load static %}
{% include 'user/includes/header.html' with title="- Dados da conta" %}
   
<main>

    {% if messages %}
    {% for message in messages %}
    <div id="alert"
        class="alert rounded-0 {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show "
        role="alert">
        <span> {{ message }} </span>
        <button type="button" class="btn-close" onclick="hidenAlert()"></button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="container">

        <form action="{% url 'userData' %}" method="post">

            <h1 class="mt-3">Seus dados</h1>

            {% csrf_token %}
            <!-- <div class="mt-3">
                <label for="image">Foto</label>
                <input class="form-control" type="file" name="" id="image">
            </div> -->

            <div class="mt-2">
                <label class="labelForm" for="id_username">Nome</label>
                {{ form.username }}
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_email">E-mail</label>
                {{ form.email }}
            </div>

            <div class="mt-2">
                <label class="labelForm" for="id_password1">Senha</label>
                {{ form.password1 }}
                <small>
                    <ul>
                        <li>Sua senha não pode ser muito parecida com suas informações pessoais.</li>
                        <li>Sua senha deve conter pelo menos 8 caracteres.</li>
                        <li>Sua senha não pode ser uma senha de usuário comum.</li>
                        <li>Sua senha não pode ser totalmente numérica.</li>
                    </ul>
                </small>
            </div>
            <div class="mt-2">
                <label class="labelForm" for="id_password2">Confirmar senha</label>
                {{ form.password2 }}
            </div>

            <input class="btn btn-info mt-4" type="submit" value="Salvar"">
            <button class="btn btn-danger mt-4" onclick="deleteConfirm('Realmente deseja deletar esta conta permanentemente?', `{% url 'removeUser' %}`)">Deletar conta</button>

        </form>
 
    </div>

</main>

{% include 'user/includes/footer.html' %}